### ISSUE TITLE
Images in README file

### ISSUE THREAD

**Issue by Aazat** [Aazat/Monet_GAN#1]
Demonstration images not displaying properly in README file, need to change the way images are loaded.

**Comment by SakuraGarden99** [comment]
Let me update README and try to improve it.

**Comment by SakuraGarden99** [comment]
![after_training](https://github.com/Aazat/Monet_GAN/assets/138879124/423f39ab-34e7-4343-990e-69a288be71a0)
![before_training](https://github.com/Aazat/Monet_GAN/assets/138879124/5faff65e-5377-4c2e-bad8-4b32a91e5dbc)
![monet_to_photo](https://github.com/Aazat/Monet_GAN/assets/138879124/ba626b42-7d93-4a75-9134-2525c9088171)
![photo_to_monet](https://github.com/Aazat/Monet_GAN/assets/138879124/6f347c43-f9cc-4d76-b8bf-32c1186d7a79)
